package com.qccr.books.lib.util.greendao;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "BOOK".
 */
@Entity
public class Book {

    @Id
    private Long id;
    private String rating;
    private String title;
    private String orginTitle;
    private String author;
    private String smallPic;
    private String mediumPic;
    private String largePic;
    private String isbn;
    private String summary;
    private String publisher;
    private String price;
    private String pages;
    private String apiUrl;

    @Generated(hash = 1839243756)
    public Book() {
    }

    public Book(Long id) {
        this.id = id;
    }

    @Generated(hash = 1087692987)
    public Book(Long id, String rating, String title, String orginTitle, String author, String smallPic, String mediumPic, String largePic, String isbn, String summary, String publisher, String price, String pages, String apiUrl) {
        this.id = id;
        this.rating = rating;
        this.title = title;
        this.orginTitle = orginTitle;
        this.author = author;
        this.smallPic = smallPic;
        this.mediumPic = mediumPic;
        this.largePic = largePic;
        this.isbn = isbn;
        this.summary = summary;
        this.publisher = publisher;
        this.price = price;
        this.pages = pages;
        this.apiUrl = apiUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRating() {
        return rating;
    }

    public void setRating(String rating) {
        this.rating = rating;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getOrginTitle() {
        return orginTitle;
    }

    public void setOrginTitle(String orginTitle) {
        this.orginTitle = orginTitle;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getSmallPic() {
        return smallPic;
    }

    public void setSmallPic(String smallPic) {
        this.smallPic = smallPic;
    }

    public String getMediumPic() {
        return mediumPic;
    }

    public void setMediumPic(String mediumPic) {
        this.mediumPic = mediumPic;
    }

    public String getLargePic() {
        return largePic;
    }

    public void setLargePic(String largePic) {
        this.largePic = largePic;
    }

    public String getIsbn() {
        return isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getPublisher() {
        return publisher;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getPages() {
        return pages;
    }

    public void setPages(String pages) {
        this.pages = pages;
    }

    public String getApiUrl() {
        return apiUrl;
    }

    public void setApiUrl(String apiUrl) {
        this.apiUrl = apiUrl;
    }

}
